baseurl = "xxx.com"
languageCode = "pt-br"
title = "Caio Almeida"
theme = "beautifulhugo"

[Params]
  logo = "img/avatar-icon.png"
  title = ""
  subtitle = "Build a beautiful and simple website in minutes"

[Author]
  name = "Some Person"
  email = "youremail@domain.com"
  facebook = "username"
  github = "username"
  twitter = "username"
  linkedin = "pub/username/X/YYY/ZZZ"
  stackoverflow = "XXXXXXX/username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
